import type { Metadata } from "next";
import { Container } from "@/components/boostrap";
import getAllPosts from "@/lib/getAllPosts";
import WelcomeMessage from "./components/WelcomeMessage";
import PostItem from "./posts/components/PostItem";

export const metadata: Metadata = {
  title: "Welcome To My Posts👋😄",
  description: "Generated by create next app",
};

export default async function Home() {
  const postsData: Promise<Posts[]> = getAllPosts();
  const posts: Posts[] = await postsData;

  return (
    <>
      <Container>
        <WelcomeMessage message="Welcome To My Posts👋😄" />
        <hr className="text-secondary px-0 mx-1" />

        <PostItem posts={posts} />
      </Container>
    </>
  );
}
